# Vectorization - 2 features
In this notebook is explained how apply vectorization on Linear Regression with 2 features

In [1]:
import numpy as np

In [2]:
x_1 = np.array([56, 48, 66, 72])
x_2 = np.array([16, 88, 10, 52])
y = np.array([13, 11, 14, 18])
x_1

array([56, 48, 66, 72])

# Manual define model

In [3]:
w_1 = 11
w_2 = 15
b = 30

# Model linear regression NON-vectorized

In [4]:
m = x_1.shape[0]
f_x = np.zeros(m)
for i in range(m):
    f_x[i] = w_1*x_1[i] + w_2*x_2[i] + b
f_x

array([ 886., 1878.,  906., 1602.])

# Model linear regression Vectorized

## Using np.dot function requires:
- x_train - is np vector of dimension (x, 1)
- w - is np vector of dimension (1,1)

In [5]:
x_1 = np.array([56, 48, 66, 72])
x_2 = np.array([16, 88, 10, 52])
x = np.c_[x_1, x_2]
print(x)
print(f'x shape: {x.shape}')

w = np.array([[11], [15]]) # same as np.array([11, 15]).reshape(-1, 1)
print(w)
print(f'w shape: {w.shape}')

b = 30

[[56 16]
 [48 88]
 [66 10]
 [72 52]]
x shape: (4, 2)
[[11]
 [15]]
w shape: (2, 1)


## Vectorized model

In [6]:
f_x = np.dot(x, w) + b
f_x

array([[ 886],
       [1878],
       [ 906],
       [1602]])

# Cost function

In [7]:
x_1 = np.array([56, 48, 66, 72])
x_2 = np.array([16, 88, 10, 52])
y = np.array([13, 11, 14, 18])

w_1 = 11
w_2 = 15
b = 30

m = x_1.shape[0]

In [8]:
cost_sum = 0
for i in range(m): 
    f_x_i = w_1 * x_1[i] + w_2 * x_2[i] + b   
    cost_i = (f_x_i - y[i]) ** 2  
    cost_sum += cost_i
total_cost = (1 / (2.0 * m)) * cost_sum  

print(f" Cost computed non-vectorized: {total_cost}")

 Cost computed non-vectorized: 944067.25


## Vectorized cost function

In [9]:
x_1 = np.array([56, 48, 66, 72])
x_2 = np.array([16, 88, 10, 52])
y = np.array([13, 11, 14, 18]) # (4, )
y = y.reshape(-1, 1) # (4, 1)

x = np.c_[x_1, x_2] # (4, 2)

w = np.array([[11], [15]]) # same as np.array([11, 15]).reshape(-1, 1)
b = 30

m = x.shape[0]

Before all numPy matrix operations all matrixes needs to have both parameters of shape

In [10]:
print(f"x.shape: {x.shape}")
print(f"y.shape: {y.shape}")
print(f"w.shape: {w.shape}")

x.shape: (4, 2)
y.shape: (4, 1)
w.shape: (2, 1)


In [11]:
f_x = np.dot(x, w) + b
cost = (f_x - y)**2
cost_sum = np.sum(cost)
total_cost = (1 / (2.0 * m)) * cost_sum

print(f" Cost computed Vectorized: {total_cost}")

 Cost computed Vectorized: 944067.25


# Gradient descent

In [12]:
x_1 = np.array([56, 48, 66, 72])
x_2 = np.array([16, 88, 10, 52])
y = np.array([13, 11, 14, 18])

w_1 = 11
w_2 = 15
b = 30

m = x_1.shape[0]

In [13]:
dJ_dw_1 = 0
dJ_dw_2 = 0
dJ_db = 0

for i in range(m):
    f_x = w_1 * x_1[i] + w_2 * x_2[i] + b
    dJ_dw_1_i = (f_x - y[i]) * x_1[i]
    dJ_dw_2_i = (f_x - y[i]) * x_2[i]
    dJ_db_i  = (f_x - y[i])
    dJ_dw_1 += dJ_dw_1_i
    dJ_dw_2 += dJ_dw_2_i
    dJ_db += dJ_db_i
dJ_dw_1 = dJ_dw_1 / m
dJ_dw_2 = dJ_dw_2 / m
dJ_db = dJ_db / m

print(f'Computed gradients non-vectorized: {dJ_dw_1}, {dJ_dw_2}, {dJ_db}')

Computed gradients non-vectorized: 77856.0, 67388.0, 1304.0


# Vectorized gradient descent

In [14]:
x_1 = np.array([56, 48, 66, 72])
x_2 = np.array([16, 88, 10, 52])
y = np.array([13, 11, 14, 18]) # (4, )
y = y.reshape(-1, 1) # (4, 1)

x = np.c_[x_1, x_2]

w = np.array([[11], [15]])
b = 30

m = x_1.shape[0]

In [15]:
f_x = np.dot(x, w) + b
cost = f_x - y
# dJ_dw = np.dot(x.T, cost) * (1/m)  
dJ_dw = np.dot(x.T, cost) * (1/m)  
dJ_db = np.sum(cost) * (1/m) 

# print(dJ_dw[0][0], dJ_dw[1][0], dJ_db)
print(f'Computed gradients vectorized: {dJ_dw[0][0]}, {dJ_dw[1][0]}, {dJ_db}')

Computed gradients vectorized: 77856.0, 67388.0, 1304.0
